### ISSUE TITLE
dbusmenu support

### ISSUE THREAD

**Issue by vovochka404** [jjk-jacky/statusnotifier#7]
Is here any plans for dbusmenu out-of-the-box support?
Or every one will have to do it by his own?

**Comment by vovochka404** [comment]
I can contribute a dbusmenu support based on libdbusmenu.
The only problem is that libdusmenu depends on gtk2/3 (there is  2 versions libdbusmenu)
This will make this lib also gtk-version dependent. Any ideas how to avoid this?

**Comment by jjk-jacky** [comment]
First off, I'm not sure what you mean by dbusmenu support? There's no
mention of menus in the specs, only a ContextMenu() method to ask to
show one.
I assume this is something that was added but never documented/added to
the specs?

Then, I'm not familiar at all with dbus menus, or libdbusmenu, but isn't
there like a client library and a server one? Where the client is used
to get & show menus from dbus, and the server send them over?
In that case, I assume only the later would be needed here, while only
the former would need to link against GTK.
If not though, I'd say linking against GTK3 probably isn't a big issue,
since it actually already link against GDK3 anyhow.

If you want to work on a patch for it, I'd be happy to merge, though I'd
like it to be optional at configure level, so one could choose whether
to build w/ dbusmenu support (and require libdbusmenu) or not.

-j
